- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        resource_group_name: "{{ rs_group }}"
        template_link: 'https://raw.githubusercontent.com/stacker2017/azure-temp/master/azureloadbalancertemp.json'
        parameters:
           storageAccountName:
              value: "{{ storage_name }}"
           adminUsername:
              value: "{{ user_name }}"
           adminPassword:
              value: "{{ password }}"          
           dnsNameforLBIP:
               value: "{{ dns_name }}"
               
